# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ai.v1 import agent_pb2 as ai_dot_v1_dot_agent__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai/v1/agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub:
    """AgentService handles AI agent workflow execution.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteAgent = channel.unary_unary(
                '/ai.v1.AgentService/ExecuteAgent',
                request_serializer=ai_dot_v1_dot_agent__pb2.AgentRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_agent__pb2.AgentResponse.FromString,
                _registered_method=True)
        self.WatchAgent = channel.unary_stream(
                '/ai.v1.AgentService/WatchAgent',
                request_serializer=ai_dot_v1_dot_agent__pb2.WatchRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_agent__pb2.AgentEvent.FromString,
                _registered_method=True)


class AgentServiceServicer:
    """AgentService handles AI agent workflow execution.
    """

    def ExecuteAgent(self, request, context):
        """ExecuteAgent triggers an async agent workflow, returning a run_id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchAgent(self, request, context):
        """WatchAgent streams agent execution progress.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteAgent,
                    request_deserializer=ai_dot_v1_dot_agent__pb2.AgentRequest.FromString,
                    response_serializer=ai_dot_v1_dot_agent__pb2.AgentResponse.SerializeToString,
            ),
            'WatchAgent': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchAgent,
                    request_deserializer=ai_dot_v1_dot_agent__pb2.WatchRequest.FromString,
                    response_serializer=ai_dot_v1_dot_agent__pb2.AgentEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.v1.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService:
    """AgentService handles AI agent workflow execution.
    """

    @staticmethod
    def ExecuteAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.AgentService/ExecuteAgent',
            ai_dot_v1_dot_agent__pb2.AgentRequest.SerializeToString,
            ai_dot_v1_dot_agent__pb2.AgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai.v1.AgentService/WatchAgent',
            ai_dot_v1_dot_agent__pb2.WatchRequest.SerializeToString,
            ai_dot_v1_dot_agent__pb2.AgentEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
