# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/v1/agent.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'ai/v1/agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61i/v1/agent.proto\x12\x05\x61i.v1\"\xb2\x01\n\x0c\x41gentRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x15\n\rworkflow_type\x18\x02 \x01(\t\x12\r\n\x05input\x18\x03 \x01(\t\x12\x33\n\x08metadata\x18\x05 \x03(\x0b\x32!.ai.v1.AgentRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01J\x04\x08\x04\x10\x05\"5\n\rAgentResponse\x12\x14\n\x0c\x61gent_run_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"$\n\x0cWatchRequest\x12\x14\n\x0c\x61gent_run_id\x18\x01 \x01(\t\"Q\n\nAgentEvent\x12\x14\n\x0c\x61gent_run_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\t2\x81\x01\n\x0c\x41gentService\x12\x39\n\x0c\x45xecuteAgent\x12\x13.ai.v1.AgentRequest\x1a\x14.ai.v1.AgentResponse\x12\x36\n\nWatchAgent\x12\x13.ai.v1.WatchRequest\x1a\x11.ai.v1.AgentEvent0\x01\x42&Z$ai-design-platform/gen/go/ai/v1;aiv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.v1.agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$ai-design-platform/gen/go/ai/v1;aiv1'
  _globals['_AGENTREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_AGENTREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_AGENTREQUEST']._serialized_start=29
  _globals['_AGENTREQUEST']._serialized_end=207
  _globals['_AGENTREQUEST_METADATAENTRY']._serialized_start=154
  _globals['_AGENTREQUEST_METADATAENTRY']._serialized_end=201
  _globals['_AGENTRESPONSE']._serialized_start=209
  _globals['_AGENTRESPONSE']._serialized_end=262
  _globals['_WATCHREQUEST']._serialized_start=264
  _globals['_WATCHREQUEST']._serialized_end=300
  _globals['_AGENTEVENT']._serialized_start=302
  _globals['_AGENTEVENT']._serialized_end=383
  _globals['_AGENTSERVICE']._serialized_start=386
  _globals['_AGENTSERVICE']._serialized_end=515
# @@protoc_insertion_point(module_scope)
