# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ai.v1 import generation_pb2 as ai_dot_v1_dot_generation__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai/v1/generation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GenerationServiceStub:
    """GenerationService handles AI text/code generation with streaming.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamGenerate = channel.unary_stream(
                '/ai.v1.GenerationService/StreamGenerate',
                request_serializer=ai_dot_v1_dot_generation__pb2.GenerateRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_generation__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.CancelGeneration = channel.unary_unary(
                '/ai.v1.GenerationService/CancelGeneration',
                request_serializer=ai_dot_v1_dot_generation__pb2.CancelRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_generation__pb2.CancelResponse.FromString,
                _registered_method=True)


class GenerationServiceServicer:
    """GenerationService handles AI text/code generation with streaming.
    """

    def StreamGenerate(self, request, context):
        """StreamGenerate performs LLM generation, returning tokens as they arrive.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelGeneration(self, request, context):
        """CancelGeneration stops an in-progress generation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GenerationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamGenerate': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamGenerate,
                    request_deserializer=ai_dot_v1_dot_generation__pb2.GenerateRequest.FromString,
                    response_serializer=ai_dot_v1_dot_generation__pb2.GenerateResponse.SerializeToString,
            ),
            'CancelGeneration': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelGeneration,
                    request_deserializer=ai_dot_v1_dot_generation__pb2.CancelRequest.FromString,
                    response_serializer=ai_dot_v1_dot_generation__pb2.CancelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.v1.GenerationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.v1.GenerationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GenerationService:
    """GenerationService handles AI text/code generation with streaming.
    """

    @staticmethod
    def StreamGenerate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai.v1.GenerationService/StreamGenerate',
            ai_dot_v1_dot_generation__pb2.GenerateRequest.SerializeToString,
            ai_dot_v1_dot_generation__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelGeneration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.v1.GenerationService/CancelGeneration',
            ai_dot_v1_dot_generation__pb2.CancelRequest.SerializeToString,
            ai_dot_v1_dot_generation__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
